#...............................................................................
# Copyright (c)
#
# The build workflow was created by : Alex Bolot and Pierre Bolot
# As part of the PhotoStore project
#
# Last modified : 04/01/2021 01:51
#
# Contact : contact.alexandre.bolot@gmail.com
#...............................................................................

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 'Build Android App'
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check-out code from branch
        uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze code for any errors.
        run: flutter analyze .

      - name: Build Android apk.
      - run: flutter build apk --target-platform android-arm64
