#...............................................................................
# Copyright (c)
#
# The quality-check workflow was created by : Alex Bolot and Pierre Bolot
# As part of the PhotoStore project
#
# Last modified : 1/3/21 11:25 PM
#
# Contact : contact.alexandre.bolot@gmail.com
#...............................................................................

name: Quality Check

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  code_quality:
    name: 'Code quality'

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
